version: 2.1

_references:
  ruby_versions: &ruby_versions
    ruby-version:
      - "3.4"
      - "3.3"
      - "3.2"
  rails_version_prefixess: &rails_version_prefixes
    rails-version-prefix:
      - "8.0"
      - "7.2"
      - "7.1"

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  test:
    parameters:
      ruby-version:
        type: string
      rails-version-prefix:
        type: string

    executor:
      name: ruby/default
      tag: <<parameters.ruby-version>>
    environment:
      RAILS_VERSION_PREFIX: <<parameters.rails-version-prefix>>
    steps:
      - checkout
      - ruby/install-deps:
          # Have to set this since there's no lockfile
          bundler-version: ">2"
          # Do not use deployment mode, because we don't have a lockfile
          path: "bundle"
          # Always install the latest versions available
          with-cache: false
      - ruby/rspec-test

workflows:
  test:
    jobs:
      - test:
          name: "test-ruby-<<matrix.ruby-version>>-rails-<<matrix.rails-version-prefix>>"
          matrix:
            parameters:
              <<: *ruby_versions
              <<: *rails_version_prefixes
  test-head:
    jobs:
      - test:
          name: "test-ruby-<<matrix.ruby-version>>-rails-main"
          matrix:
            parameters:
              <<: *ruby_versions
              rails-version-prefix:
                - main
