version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  test:
    parameters:
      ruby-version:
        type: string

    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - ruby/install:
          version: <<parameters.ruby-version>>
      - ruby/install-deps:
          # Have to set this since there's no lockfile
          bundler-version: ">2"
          # Do not use deployment mode, because we don't have a lockfile
          path: "bundle"
          # Always install the latest versions available
          with-cache: false
      - ruby/rspec-test

workflows:
  test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version:
                - "3.0.6"
                - "3.2.2"
