version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  build:
    working_directory: ~/acts_as_scrubbable
    docker:
      - image: cimg/ruby:3.2.2

    steps:
      - checkout
      - ruby/install-deps:
          # Guess we have to keep updating this
          bundler-version: 2.5.3
          # Always install the latest versions available
          with-cache: false
      - ruby/rspec-test
